import Image from "next/image";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";
import { ClerkProvider, ClerkLoading, ClerkLoaded } from "@clerk/nextjs";
import { dark } from "@clerk/themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Imagen Wall Art",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider appearance={{ baseTheme: dark }}>
			<html lang='en'>
				<body className={inter.className}>
					<ClerkLoading>
						<div className=' flex min-h-screen items-center justify-center'>
							<Image
								src={"/full-logo.png"}
								alt={"Loading"}
								width={450}
								height={450}
								className='animate-fadeIn' // Use the fadeIn animation class
							/>
						</div>
					</ClerkLoading>
					<ClerkLoaded>
						<div>
							<Navbar />
							{children}
							<Footer />
						</div>
					</ClerkLoaded>
				</body>
			</html>
		</ClerkProvider>
	);
}
